const groups=[{id:'croissants',name:'Croissants',description:'Golden layers. Deliciously flaky.',photo:'croissant',items:[['Cheese',100000],['Chocolate',100000],['Zaatar',100000],['Pizza',150000],['Kunafa',300000],['Lotus',200000],['Kinder',200000],['Pistachio',200000]]},{id:'doughnuts',name:'Doughnuts',description:'A soft, sweet little pick-me-up.',photo:'doughnut',items:[['Plain',100000],['Strawberry Filled',200000],['Crème Pâtissière Filled',200000],['Chocolate Crème Pâtissière Filled',200000]]},{id:'saj',name:'Saj',description:'Warm, folded & full of flavor.',photo:'saj-photo',items:[['Zaatar',70000],['Labne + Zaatar',150000],['Labne',100000],['Zaatar + Cheese',200000],['Keshek',150000],['Aakawi Cheese',200000],['Bulghari Cheese',250000],['Halloum Cheese',230000],['Kashkawen Cheese',250000],['3 Cheese',350000,'Aakawi + Mozzarella + Kashkawan'],['Halloum + Pesto',260000],['Martadella',250000],['Martadella + Cheese',300000],['Turkey',300000],['Turkey + Cheese',350000],['Sojok',400000],['Sojok + Cheese',450000],['Extra Khodra',50000,'Vegetable add-on']]}];
groups.push(...[{"id":"hot-drinks","name":"Hot Drinks","description":"A warm cup for every craving.","items":[["Espresso",50000],["Nescafe",80000],["Cappuccino",60000],["Hot Chocolate",80000]]},{"id":"cold-drinks","name":"Cold Drinks","description":"Cool down with your favorite sip.","items":[["Soft Drink",80000],["Rim Sparkling Water",60000],["Rim Sparkling Water (Flavored)",80000],["Via Sparkling Water",80000],["Ice Tea",80000],["Ice Coffee",80000],["Juice",40000],["Water",25000]]},{"id":"argile","name":"Argile","description":"In store only.","inStoreOnly":true,"items":[["Tefehten",400000],["Hamod + Mint",300000]]}]);
groups.splice(groups.findIndex(g=>g.id==="argile"),0,{"id":"frisco","name":"Frisco","description":"Fresh-made iced drinks in your favorite flavor.","items":[["Strawberry — Medium",100000],["Strawberry — Large",200000],["Mango — Medium",100000],["Mango — Large",200000],["Banana Milkshake — Medium",100000],["Banana Milkshake — Large",200000]]});
document.querySelector(".category-links").innerHTML=groups.map((g,i)=>`<a href="#${g.id}">${String(i+1).padStart(2,"0")} <span>${g.name}</span></a>`).join("");
const products=groups.flatMap(g=>g.items.map((p,i)=>({id:`${g.id}-${i}`,name:p[0],price:p[1],detail:p[2],category:g.name,inStoreOnly:!!g.inStoreOnly})));const cart=new Map();const money=n=>`${n.toLocaleString('en-US')} LL`;const dialog=document.querySelector('#cartDialog');let toastTimer;
document.querySelector('#menuSections').innerHTML=groups.map(g=>`<section class="menu-group" id="${g.id}"><div class="group-intro"><h3>${g.name}</h3><p>${g.description}</p>${g.photo?`<div class="photo small-photo ${g.photo}" role="img" aria-label="${g.name} from the Crovella menu"></div>`:""}</div><div class="product-list">${products.filter(p=>p.category===g.name).map(p=>`<article class="product"><div><h4>${p.name}</h4>${p.detail?`<small>${p.detail}</small>`:''}<p>${money(p.price)}</p></div>${p.inStoreOnly?`<span class="in-store">In store</span>`:`<button class="add" data-add="${p.id}" aria-label="Add ${p.name} ${p.category} to cart">+</button>`}</article>`).join('')}</div></section>`).join('');
function summary(){return [...cart].map(([id,quantity])=>({...products.find(p=>p.id===id),quantity}));}
function update(){const items=summary(),count=items.reduce((n,p)=>n+p.quantity,0),total=items.reduce((n,p)=>n+p.quantity*p.price,0);document.querySelector('#cartCount').textContent=count;const label=document.querySelector('#orderLabel');label.hidden=count===0;label.textContent=count?`Order · ${count}`:'';document.querySelector('#whatsapp').setAttribute('aria-label',count?`Review order with ${count} items`:'Contact Crovella on WhatsApp');document.querySelector('#cartItems').innerHTML=items.length?items.map(p=>`<div class="cart-row"><div><strong>${p.name}</strong><p>${p.category} · ${money(p.price*p.quantity)}</p></div><div class="quantity"><button data-change="${p.id}" data-delta="-1" aria-label="Remove one ${p.name}">−</button><span>${p.quantity}</span><button data-change="${p.id}" data-delta="1" aria-label="Add one ${p.name}">+</button></div></div>`).join(''):'<p class="empty">Your bag is waiting for something delicious.</p>';document.querySelector('#subtotal').textContent=money(total);document.querySelector('#checkout').hidden=!count;document.querySelector('.cart-bottom').hidden=!count;return {items,count,total};}
function add(id){if(!products.some(p=>p.id===id&&!p.inStoreOnly))throw new Error('Unknown menu item');cart.set(id,(cart.get(id)||0)+1);update();animateCart();const toast=document.querySelector('#toast');toast.textContent='Added to your bag';toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1800);return summary();}
document.addEventListener('click',e=>{const addButton=e.target.closest('[data-add]');if(addButton)add(addButton.dataset.add);const change=e.target.closest('[data-change]');if(change){const id=change.dataset.change;const qty=(cart.get(id)||0)+Number(change.dataset.delta);qty>0?cart.set(id,qty):cart.delete(id);update();}});
document.querySelector('#cartButton').onclick=()=>dialog.showModal();document.querySelector('#closeCart').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function whatsapp(message){window.open(`https://wa.me/96170042731?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');}
document.querySelector('#whatsapp').onclick=()=>cart.size?dialog.showModal():whatsapp('Hello Crovella! I’d like to ask about your menu.');document.querySelector('#checkout').onclick=()=>{const {items,total}=update();if(!items.length)return;whatsapp(`Hello Crovella! I’d like to order:\n\n${items.map(p=>`${p.quantity} × ${p.category} — ${p.name}: ${money(p.price*p.quantity)}`).join('\n')}\n\nSubtotal: ${money(total)}\nPlease confirm availability and delivery fees. Thank you!`);};update();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'stage_cart_item',description:'Add a menu item to the temporary cart for review. Does not send an order.',inputSchema:{type:'object',properties:{id:{type:'string',enum:products.filter(p=>!p.inStoreOnly).map(p=>p.id)}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.id!=='string')throw new Error('A valid menu item ID is required');return add(input.id);}})).catch(()=>{});}catch{}}

function animateCart(){if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;['#cartCount','#whatsapp'].forEach(selector=>{const element=document.querySelector(selector);element.classList.remove('cart-pop');void element.offsetWidth;element.classList.add('cart-pop');element.addEventListener('animationend',()=>element.classList.remove('cart-pop'),{once:true});});}
if('IntersectionObserver' in window && !window.matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}});},{threshold:.08});document.querySelectorAll('.section-heading,.group-intro,.product,.contact-section').forEach((element,index)=>{element.style.setProperty('--reveal-delay',(index%3)*65+'ms');element.classList.add('reveal-ready');observer.observe(element);});}
